TOKEN = '6209429435:AAGbSIYu3tbqUXxGXzs55noiYBpQyE3Pi-U'

# Список доступных для конвертирования валют
curency_dict: dict = {'рубль': 'RUB',
                      'доллар': 'USD',
                      'евро': 'EUR',
                      "биткоин": "BTC",
                      "эфириум": "ETH",
                      "tether": "USDT",
                      "ripple": "XRP",
                      "bnb": "BNB",
                      "usdc": "USDC",
                      "lido_staked_ether": "STETH",
                      "solana": "SOL",
                      "кардано": "ADA",
                      "dogecoin": "DOGE",
                      "toncoin": "TON",
                      "tron": "TRX",
                      "chainlink": "LINK",
                      "polygon": "MATIC",
                      "polkadot": "DOT",
                      "wrapped_bitcoin": "WBTC",
                      "лайткоин": "LTC",
                      "shiba_inu": "SHIB",
                      "биткойн_кэш": "BCH",
                      "avalanche": "AVAX",
                      "uniswap": "UNI",
                      "stellar": "XLM",
                      "dai": "DAI",
                      "leo_token": "LEO",
                      "trueusd": "TUSD",
                      "okb": "OKB",
                      "монеро": "XMR",
                      "эфириум_классик": "ETC",
                      "cosmos_hub": "ATOM",
                      "filecoin": "FIL",
                      "hedera": "HBAR",
                      "cronos": "CRO",
                      "internet_computer": "ICP",
                      "busd": "BUSD",
                      "aptos": "APT",
                      "lido_dao": "LDO",
                      "near_protocol": "NEAR",
                      "vechain": "VET",
                      "quant": "QNT",
                      "injective": "INJ",
                      "arbitrum": "ARB",
                      "aave": "AAVE",
                      "kaspa": "KAS",
                      "optimism": "OP",
                      "mantle": "MNT",
                      "the_graph": "GRT",
                      "maker": "MKR",
                      "multiversx": "EGLD",
                      "immutablex": "IMX",
                      "rocket_pool_eth": "RETH"
                      }

if __name__ == '__main__':
    print(curency_dict)
